apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-user-list
  namespace: grafana
data:
  users.json: |
    [
      { "name": "User 1", "login": "user1", "role": "Viewer", "email": "user1@example.com", "password": "generatedPassword123!" },
      { "name": "User 2", "login": "user2", "role": "Editor", "email": "user2@example.com", "password": "anotherRandomPass456@" },
      { "name": "User 3", "login": "user3", "role": "Admin", "email": "user3@example.com", "password": "anotherRandomPass123123@" }
    ]
