admin:
  existingSecret: grafana-admin-secret

service:
  type: NodePort

image:
  repository: grafana/grafana
  tag: "11.5.1"

persistence:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi

# Specify additional containers to be added to the Grafana pod
extraContainers: |
  - name: grafana-users-provision
    image: docker.io/library/grafana-users-provision:1.0.0
    imagePullPolicy: Never
    command:
      - sh
      - -c
      - |
        echo "Waiting for Grafana to be ready..."
        until wget -qO- http://localhost:3000/api/health > /dev/null 2>&1; do
          echo "Grafana is not ready yet. Retrying in 100 seconds..."
          sleep 60
        done
        echo "Grafana is ready. Starting user provisioning..."
        /usr/local/bin/grafana-users-provision
        echo "User provisioning complete. Exiting..."
    volumeMounts:
      - name: user-config
        mountPath: /etc/grafana/users.json
        subPath: users.json

# Define volumes for the additional containers (not mounted directly in Grafana pod)
extraContainerVolumes:
  - name: user-config
    configMap:
      name: grafana-user-list
